service: work-schedule
app: personal
org: luanapp

plugins:
  - serverless-offline

frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  stage: dev
  region: sa-east-1

  environment:
    ENTRANCE_SHEET_ID: ${env:ENTRANCE_SHEET_ID}
    EXIT_SHEET_ID: ${env:EXIT_SHEET_ID}
    BALANCE_SHEET_ID: ${env:BALANCE_SHEET_ID}

functions:
  hello:
    handler: src/handler.makeWorkSchedule
    events:
      - schedule: rate(1 minutes)
      # - schedule: cron(* 1 ? * MON-FRI *)
