version: 2.1

orbs:
  serverless: circleci/serverless-framework@1.0.1
  aws-cli: circleci/aws-cli@1.3.2
  node: circleci/node@4.1.0

node-executor: &node-executor
  executor:
    name: node/default
    tag: '12'

node-image: &node-image
  docker:
    - image: circleci/node:12.14.1

yarn-install: &yarn-install
  node/install-packages:
    pkg-manager: yarn

only-main: &only-main
  filters:
    branches:
      only:
        - main
ignore-main: &ignore-main
  filters:
    branches:
      ignore:
        - main

jobs:
  build:
    <<: *node-executor
    <<: *node-image
    steps:
      - checkout
      - <<: *yarn-install
  test:
    <<: *node-executor
    <<: *node-image
    steps:
      - checkout
      - <<: *yarn-install
      - run: yarn test
  deploy:
    executor: serverless/default
    <<: *node-image
    parameters:
      stage:
        type: string
        default: dev
    steps:
      - checkout
      - <<: *yarn-install
      - serverless/setup:
          app-name: personal-stuff
          org-name: luanapp
      - run: echo $CREDENTIALS | base64 --decode > credentials.json
      - run: echo $TOKEN | base64 --decode > token.json
      - run: sls deploy -v --stage << parameters.stage >>

workflows:
  version: 2.1
  deploy-dev:
    jobs:
      - build:
          <<: *ignore-main
      - test:
          requires:
            - build
      #- deploy:
      #    stage: dev
      #    requires:
      #      - build
  deploy-prod:
    jobs:
      - build:
          <<: *only-main
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - test
      #- deploy:
      #    stage: prod
      #    requires:
      #      - hold
