version: 2.1

orbs:
  serverless: circleci/serverless-framework@1.0.1
  aws-cli: circleci/aws-cli@1.3.2
  node: circleci/node@4.1.0

only-master: &only-master
  filters:
    branches:
      only:
        - master
ignore-master: &ignore-master
  filters:
    branches:
      ignore:
        - master

jobs:
  build:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
  test:
    executor:
      name: node/default
      tag: '12'
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn test
  deploy:
    executor: serverless/default
    parameters:
      stage:
        type: string
        default: dev
    steps:
      - checkout
      - serverless/setup:
          app-name: personal-stuff
          org-name: luanapp
      - run: echo $CREDENTIALS | base64 --decode > credentials.json
      - run: echo $TOKEN | base64 --decode > token.json
      - run: sls deploy -v --stage << parameters.stage >>

workflows:
  version: 2.1
  deploy-dev:
    jobs:
      - build:
        <<: *ignore-master
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - test
      - deploy:
          stage: dev
          requires:
            - hold
  deploy-prod:
    jobs:
      - build:
          <<: *only-master
      - test:
          requires:
            - build
      - deploy:
          stage: prod
          requires:
            - build
