version: 2.1

orbs:
  serverless: circleci/serverless-framework@1.0.1
  aws-cli: circleci/aws-cli@1.3.2
  node: circleci/node@4.1.0

yarn-install: &yarn-install
  node/install-packages:
    pkg-manager: yarn

only-main: &only-main
  filters:
    branches:
      only:
        - main
ignore-main: &ignore-main
  filters:
    branches:
      ignore:
        - main

jobs:
  test:
    executor:
      name: node/default
      tag: '12'
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - <<: *yarn-install
      - run: yarn test
  deploy:
    executor: serverless/default
    docker:
      - image: circleci/node:12.14.1
    parameters:
      stage:
        type: string
        default: dev
    steps:
      - checkout
      - <<: *yarn-install
      - serverless/setup:
          app-name: personal-stuff
          org-name: luanapp
      - run: echo $CREDENTIALS | base64 --decode > credentials.json
      - run: echo $TOKEN | base64 --decode > token.json
      - run: sls deploy -v --stage << parameters.stage >>

workflows:
  version: 2.1
  deploy-dev:
    jobs:
      - test:
          <<: *ignore-main
      - hold:
          type: approval
          requires:
            - test
      - deploy:
          stage: dev
          requires:
            - hold
  deploy-prod:
    jobs:
      - test:
          <<: *only-main
      - deploy:
          stage: prod
          requires:
            - test
