version: 2.1

orbs:
  serverless: circleci/serverless-framework@1.0.1
  aws-cli: circleci/aws-cli@1.3.2
  node: circleci/node@4.1.0

jobs:
  deploy:
    executor: serverless/default
    docker:
      - image: circleci/node:12.14.1
    parameters:
      stage:
        type: string
        default: dev
    steps:
      - checkout
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - serverless/setup:
          app-name: personal-stuff
          org-name: luanapp
      - run: echo $CREDENTIALS | base64 --decode > credentials.json
      - run: echo $TOKEN | base64 --decode > token.json
      - run: sls deploy -v --stage << parameters.stage >>

workflows:
  version: 2.1
  deploy-dev:
    jobs:
      - deploy:
          stage: dev
          filters:
            branches:
              ignore:
                - master
